#!/usr/bin/env bash

# Autor: Jesher Minelli Alves, https://github.com/jesherdevsk8/Shell-Script/blob/master/Express%C3%B5es%20Regulares/Extraindo_Dados/extraindo_letra.sh
# ./nome-programa.sh - É um programa que faz tal coisa 
# Data: 07 dez 2021
# Versão: 1.0
# Licença: GPL

# ------------- VARIÁVEIS


# ------------- FUNÇÃO


# ------------- TESTE


# ------------- INTERAÇÃO COM USÚARIO


# ------------- EXECUÇÃO